# Generated by Django 4.2.2 on 2025-04-21 04:33

import cardekho_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0002_carlist_chassisnumber_carlist_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='chassisnumber',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[cardekho_app.models.alphanumeric]),
        ),
    ]
