# Generated by Django 4.2.2 on 2025-04-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0003_showroomlist_alter_carlist_chassisnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='cardekho_app.showroomlist'),
        ),
    ]
